services:
  conductor:
    build:
      context: .
    environment:
      - URL=${URL:-https://google.com}
      - RTMP=${RTMP:-rtmp://host.docker.internal:1935/live/stream}
      - DISPLAY=:99
      - OVERLAY=:98
      - WIDTH=1920
      - HEIGHT=1080
      - FPS=30
      - BITRATE=3000
      - AUDIO_BITRATE=128000
      - MAX_RETRIES=3
      - RETRY_DELAY=5000
    mem_limit: 2g
    restart: unless-stopped
    ports:
      - "9222:9222"

networks:
  default:
    driver: bridge
